name: Build and Release

on:
  - push

jobs:
  build-pnpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build x86_64 Software
        run: pnpm dist -l --x64
      
      - name: Upload dist for next stage
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  build-flatpak-and-release:
    runs-on: ubuntu-latest
    needs: build-pnpm
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Build Flatpak Package
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: sh.cider.Cider.flatpak
          manifest-path: flatpak/sh.cider.Cider.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Set Release Version
        if: startsWith(github.ref, 'refs/tags/')
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/cider_1.6.2_amd64.deb
            ./dist/sh.cider.Cider-1.6.2.AppImage
            ./sh.cider.Cider.flatpak
